name: Generate Crescente Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Generate github-snake-crescente.svg (Node 24 Compatible)
        uses: raphaelolimpio/snake-builder-actions/crescente-mode@v1
        with:
          github_user_name: ${{ github.repository_owner }}
          # Define as cores da sua cobrinha crescendo
          crescente_color: "#0175C2" # Azul igual ao seu banner
          background_color: "transparent"

      - name: Push github-snake-crescente.svg to output branch
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
